version: "3.8"

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:latest
    container_name: homeassistant
    restart: unless-stopped
    environment:
      - TZ=Europe/Brussels
    privileged: true
    volumes:
      - "./config:/config"
    networks:
      - iot
    ports:
      - "8123:8123"
networks:
  iot:
    name: IOT_Net
    driver: bridge


#network_mode: "host"
