services:
  mosquitto:
    image: eclipse-mosquitto:latest
    environment:
      - TZ=Europe/Brussels
    container_name: mosquitto-qbus
    restart: unless-stopped
    ports:
      - "11883:1883"
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    networks:
      - iot
networks:
  iot:
    name: IOT_Net
    driver: bridge
